
[device]
adapter = hci0
mac_addr = CC:45:A5:XX:YY:ZZ  
alias = BT-TH-A58A7XYZ
type = RNG_CTRL
device_id = 255 

[data]
enable_polling = false # periodically read data
poll_interval = 60 # read data interval (seconds)
temperature_unit = C # F = Fahrenheit, C = Celsius
fields = #leave empty for all fields

[remote_logging]
enabled = false


[mqtt]
enabled = false

[pvoutput]
# free accounts has a cap of max one request per minute.
enabled = false

